# Generated by Django 5.2.8 on 2025-11-25 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('madrasa_name', models.CharField(max_length=30)),
                ('cls_madrasa', models.IntegerField()),
                ('student_name', models.CharField(max_length=40)),
                ('father_name', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=15)),
                ('category', models.CharField(max_length=80)),
                ('chest_no', models.IntegerField()),
                ('house_name', models.CharField(max_length=20)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fest.participant')),
            ],
        ),
    ]
